/**
 * Template Repository — Stub Adapter
 *
 * Copy this file and implement each method for your own database
 * (MongoDB, MySQL, Firestore, etc.). Then pass the object to createModule():
 *
 *   const myRepo = createMyRepository();
 *   app.use('/api/documents', docUpload.createModule({ repository: myRepo }));
 *
 * Method signatures and expected return types are documented below.
 */

function createMyRepository() {
  return {

    /**
     * Insert a new document record.
     * @param {string} id          — UUID generated by the service
     * @param {string} applicantId — e.g. "STU-001"
     * @param {string} docType     — one of: "transcript", "cnic", "photo"
     * @param {string} fileName    — original file name
     * @param {Buffer} fileData    — raw file bytes (BLOB)
     * @param {number} fileSize    — file size in bytes
     * @param {string} mimeType    — e.g. "application/pdf", "image/png"
     */
    async insertDocument(id, applicantId, docType, fileName, fileData, fileSize, mimeType) {
      // TODO: INSERT into your database
    },

    /**
     * List documents, optionally filtered by applicantId.
     * @param {string|null} applicantId — filter or null for all
     * @returns {Array<object>} each object: { id, applicant_id, document_type, file_name, file_size, mime_type, uploaded_at, status }
     *   Do NOT include file_data for performance.
     */
    async findDocuments(applicantId) {
      // TODO: SELECT … return array
      return [];
    },

    /**
     * Get a single document's metadata by id.
     * @param {string} id
     * @returns {object|null} { id, applicant_id, document_type, file_name, file_size, mime_type, uploaded_at, status }
     */
    async findDocumentById(id) {
      // TODO: SELECT … return one row or null
      return null;
    },

    /**
     * Get a document's file data for download.
     * @param {string} id
     * @returns {object|null} { id, file_name, mime_type, file_data(Buffer) }
     */
    async findDocumentFileById(id) {
      // TODO: SELECT … return one row or null; file_data should be a Buffer
      return null;
    },

    /**
     * Delete a document by id.
     * @param {string} id
     */
    async deleteDocumentById(id) {
      // TODO: DELETE FROM …
    },

    /**
     * Update a document's status.
     * @param {string} id
     * @param {string} status — one of: "pending", "verified", "rejected"
     */
    async updateDocumentStatus(id, status) {
      // TODO: UPDATE …
    },
  };
}

module.exports = { createMyRepository };
